### ISSUE TITLE
Node gyp install error

### ISSUE THREAD

**Issue by PierBover** [codercom/bugs#121]
**Describe the bug**
I'm trying to install a Vue project but I'm getting this error when doing `npm install`.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.1 install: `node-pre-gyp install --fallback-to-build --library=static_library
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.9.1 install script.
```

**To Reproduce**
I'm not sure what package needs GYP but here's my list of dependencies:
```
  "dependencies": {
    "bootstrap-vue": "^2.0.0-rc.1",
    "eslint-plugin-html": "^4.0.2",
    "firebase": "^4.10.1",
    "mini-signals": "^1.2.0",
    "sanitize-filename": "^1.6.1",
    "uuid": "^3.2.1",
    "vee-validate": "^2.0.4",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.7.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.6",
    "sass-resources-loader": "^1.3.2",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  }
```

**Comment by PierBover** [comment]
Here is the full error:

```
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled
gyp ERR! stack Error: Python executable "/coder/bin/python" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.gyp ERR! stack     at PythonFinder.failPythonVersion (/coder/volume/node/10.5.0/lib/node_module
s/npm/node_modules/node-gyp/lib/configure.js:492:19)es/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=stat
ic_library" "--module=/coder/mnt/pier/media-site/media-site-admin-vue/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module
y gyp.gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.gyp ERR! stack     at PythonFinder.<anonymous> (/coder/volume/node/10.5.0/lib/node_modules/npm/gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)gyp ERR! System Linux 4.18.0-041800rc7-genericgyp ERR! command "/coder/volume/node/10.5.0/bin/node" "/coder/volume/node/10.5.0/lib/node_modulgrpc/node_modules/brace-expansion/.nfs000000000000e275000003de'
```

**Comment by kylecarbs** [comment]
Thanks for the report. We'll add python2.

**Comment by jaymeramsay** [comment]
Linking this feature request here: https://github.com/codercom/features/issues/114
